# By: Carrie Sundra
# Alpenglow Industries
# Copyright 2021

# What is does:
# Makes shipping orders from multiple platforms less of a pain in the ass.
# Reads multiple order export files, automatically detects the plaform they were generated by,
# and generates a single combined file that easily imports into Shippo using "default" template.
# Also uses an external ProductShippingInfo spreadsheet to better calculate package weights and
# to fill in item names for platforms that don't include those in the export (Digi-Key).
# To use, put all order export files in same folder as this script, then run script.
# - order export default filenames are fine as they all contain "orders"
# - you'll need to create a ProductShippingInfo.csv file, see the example
# - file generated for shippo is called shippoOrders.csv

# How it works:
# - generates a list of all csv files that start with the word "orders"
# - generates a shippoOrders file with proper headers for shippo importing
# - loops through the orders file list, does the following for each file:
# - detects the platform it came from based on field names
# - does platform-specific tasks to format the file properly for a dictionary read
#   - generates any missing fields/keys/column headers and appends them
#   - proper format is for order-specific info & first item ordered to be on first line
#   - if the customer ordered more items, only order #, order date, and item info
#     is on following lines
# - opens the now properly-formatted csv as a dictionary
# - looks up item weights from ProductShippingInfo.csv and calculates total order weight
# - does a few more platform-specific pieces of data manipulation that's easier to do here
# - correlates the shippo and order export headers using dictionary keys & field names
#   originally defined in platform-specific if statements
# - appends data in proper format for shippo to shippoOrders.csv
# - moves the orders file into a "processed" folder
# - repeats for next file

import csv, os, shutil

def getWeight(itemNum):
    infoFile = open('ProductShippingInfo.csv', 'r')
    shipInfo = csv.DictReader(infoFile)
    for row in shipInfo:
        if (row['Item'] == itemNum):
            return row['Weight']
#    return 0.063  # if nothing matches condition - needs testing

def getDesc(itemNum):
    infoFile = open('ProductShippingInfo.csv', 'r')
    shipInfo = csv.DictReader(infoFile)
    for row in shipInfo:
        if (row['Item'] == itemNum):
            return row['Description']

# creates a file to pull into Shippo, with header names
# does this in "write" mode to overwrite prior file
outputFile = open('shippoOrders.csv', "w")
shippoHeader =  ["Order Number", "Order Date", "Recipient Name", "Email", "Phone",
                "Company", "Street Line 1", "Street Line 2", "City", "State/Province", "Zip/Postal Code",
                "Country", "Item Title", "SKU", "Quantity", "Item Price", "Item Weight", "Item Weight Unit",
                "Order Amount", "Order Currency", "Order Weight", "Order Weight Unit"]
shippoOrders = csv.DictWriter(outputFile, fieldnames = shippoHeader, lineterminator = '\n')
shippoOrders.writeheader()
outputFile.close()

# Creates a list of all "orders" files in the directory
orderFiles = []
i = 0
print('File List:')
for file in os.listdir():
    if file.startswith('orders') and file.endswith('csv'):
        orderFiles.append(file)
        print(file)
print('')

orderPlatform = 'none'

# main loop that parses each "orders" file in the directory
for file in orderFiles:

    inputFile = open(file)
    ordersCSV = csv.reader(inputFile)
    ordersRaw = list(ordersCSV)
    inputFile.close()

    fields = ordersRaw[0]

    # identifies the platform the orders originate with and defines
    # fields according to that platform's order export format
    if fields[0] == 'Order #':
        orderPlatform = 'Weebly'
        hON = 'Order #'
        hOD = 'Date'
        hFN = 'Shipping First Name'
        hLN = 'Shipping Last Name'
        hEm = 'Shipping Email'
        hPh = 'Shipping Phone'
        hCo = 'Shipping Company'
        hSL1 = 'Shipping Address'
        hSL2 = 'Shipping Address 2'
        hCi = 'Shipping City'
        hSt = 'Shipping Region'
        hZp = 'Shipping Postal Code'
        hCn = 'Shipping Country'
        hIT = 'Product Name'
        hIO = 'Product Options'
        hSKU = 'Product SKU'
        hQty = 'Product Quantity'
        hIP = 'Product Price'
        hOA = 'Total'
    elif fields[0] == 'Order ID':
        orderPlatform = 'Tindie'
        hON = 'Order ID'
        hOD = 'Order Date'
        hFN = 'First Name'
        hLN = 'Last Name'
        hEm = 'Email'
        hPh = 'Phone'
        hCo = 'Company'
        hSL1 = 'Street'
        hSL2 = 'Street2'
        hCi = 'City'
        hSt = 'State/Province'
        hZp = 'Postal/Zip Code'
        hCn = 'Country'
        hIT = 'Product Title'
        hIO = 'Option Summary'
        hSKU = 'Model Number'
        hQty = 'Quantity'
        hIP = 'Unit Price'
        hOA = 'Order Total'
    else:
        orderPlatform = 'DigiKey'
        hON = 'Order number'
        hOD = 'Date created'
        hFN = 'Shipping address first name'
        hLN = 'Shipping address last name'
        hEm = 'Email'
        hPh = 'Shipping address phone'
        hCo = 'Shipping address company'
        hSL1 = 'Shipping address street 1'
        hSL2 = 'Shipping address street 2'
        hCi = 'Shipping address city'
        hSt = 'Shipping address state'
        hZp = 'Shipping address zip'
        hCn = 'Shipping address country'
        hIT = 'Item Name'
        hIO = 'Item Option'
        hSKU = 'Offer SKU'
        hQty = 'Quantity'
        hIP = 'Unit price'
        hOA = 'Total order amount incl. VAT (including shipping charges)'

    print(file + ' is from ' + orderPlatform)

    if orderPlatform == 'Weebly':
        # The following formats a Weebly file into an orders.csv file that's properly
        # organized for turning into a dictionary.
        # Weebly does not put item info in the first line, a single item order will have 2 lines with
        # the first line being all info common to the order, and second (and following lines) product info
        # Therefore, before reading it as a dictionary, must merge 1st and 2nd lines of each order.

        orderCol = fields.index(hON)
        productCol = fields.index(hIT)

        i = 1
        j = 0
        while i < len(ordersRaw) - 1 :
            if (ordersRaw[i][orderCol] == ordersRaw[i+1][orderCol] and ordersRaw[i][productCol] == '') :  # identifies start of new order by blank product name
                for j in range(len(ordersRaw[0])) :         # looks for blank cells, copies content from record below
                    if ordersRaw[i][j] == '' :
                        ordersRaw[i][j] = ordersRaw[i+1][j]
                del ordersRaw[i+1]                          # deletes now duplicate second order line
            i+=1

        # adds a blank "Company" column
        missingCol = 0;
        if hCo not in fields:
            missingCol = 1

        outputFile = open(file, 'w', newline='')  # newline needed to prevent double-spacing
        ordersCSV = csv.writer(outputFile)
        i = 0
        for i in range(len(ordersRaw)) :
            if missingCol:
                if i == 0:
                    ordersRaw[i].append(hCo)
                else:
                    ordersRaw[i].append('')
            ordersCSV.writerow(ordersRaw[i])    # overwrites original orders file with properly formatted one
        outputFile.close()

    if orderPlatform == 'Tindie':
        # adds a blank "Street2" column

        missingCol = 0;
        if hSL2 not in fields:
            missingCol = 1

        outputFile = open(file, 'w', newline='')
        ordersCSV = csv.writer(outputFile)
        i = 0
        for i in range(len(ordersRaw)) :
            if missingCol:
                if i == 0:
                    ordersRaw[i].append(hSL2)
                else:
                    ordersRaw[i].append('')
            ordersCSV.writerow(ordersRaw[i])
        outputFile.close()

    if orderPlatform == 'DigiKey':
        # adds blank columns for email, item title, and item option

        missingCol = 0;
        if hEm not in fields:
            missingCol = 1

        outputFile = open(file, 'w', newline='')
        ordersCSV = csv.writer(outputFile)
        i = 0
        for i in range(len(ordersRaw)) :
            if missingCol:
                if i == 0:
                    ordersRaw[i].append(hEm)
                    ordersRaw[i].append(hIT)
                    ordersRaw[i].append(hIO)
                else:
                    ordersRaw[i].append('')
                    ordersRaw[i].append('')
                    ordersRaw[i].append('')
            ordersCSV.writerow(ordersRaw[i])
        outputFile.close()

    # opens properly formatted orders file and reads into a "dictionary" which is more like a database
    # than an array/list.  No concept of order or ability to operate on previous/next rows.
    # The first row is translated to header names/labels/keys.  Handy for equating fields between files.
    inputFile = open(file)
    orders = csv.DictReader(inputFile)

    # only grabs individual weight data and adds to a separate list
    weightCount = []
    for row in orders:
        itemWeight = getWeight(row[hSKU])
        if itemWeight is None:
            itemWeight = 0.063
        itemDesc = getDesc(row[hSKU])  # mainly for DigiKey orders that don't have an Item Title, gets it from ProductShippingInfo.csv
        weightCount.append([row[hON], int(row[hQty]), float(itemWeight), " ", itemDesc])

    # goes through weight data and calculates overall order weight
    # adds 1 oz to all orders to account for bubble packaging
    i = 0
    orderWeight = 0
    while (i < len(weightCount)) :
        begIndex = i
        orderWeight = weightCount[i][1] * weightCount[i][2]   # order weight is the total weight of first line of items
        if i+1 < len(weightCount):
            while (weightCount[i][0] == weightCount[i+1][0]):
                orderWeight += (weightCount[i+1][1] * weightCount[i+1][2])
                if i+2 == len(weightCount):
                    break
                else: i += 1
        orderWeight += 0.063
        weightCount[begIndex][3] = orderWeight
        i += 1

    # resets file to re-read
    inputFile.seek(0)
    orders = csv.DictReader(inputFile)

    # reopens in append mode
    outputFile = open('shippoOrders.csv', "a")
    shippoOrders = csv.DictWriter(outputFile, fieldnames = shippoHeader, lineterminator = '\n')

    # final adjustments, writes shippoOrders output file
    rowNum = 0
    for row in orders:

        # Tindie orders - makes our great country readable to Shippo
        if "United States of America" in row[hCn]:
            row[hCn] = "USA"

        # DigiKey orders - adds the item title grabbed from ProductShippingInfo.csv
        if row[hIT] == '':
            row[hIT] = weightCount[rowNum][4]

        # writes out all final values to shippoOrders.csv
        # concatenates first and last names into single recipient name
        # concatenates Product Name and Option into a single Item Title
        shippoOrders.writerow({'Order Number': row[hON], 'Order Date': row[hOD], 'Email': row[hEm],
            'Company': row[hCo],'Phone': row[hPh], 'Street Line 1': row[hSL1], 'Street Line 2': row[hSL2], 'City': row[hCi],
            'State/Province': row[hSt],'Zip/Postal Code': row[hZp], 'Country': row[hCn],
            'Recipient Name': row[hFN] + " " + row[hLN], 'Item Title': row[hIT] + " " + row[hIO],
            'SKU': row[hSKU], 'Quantity': row[hQty], 'Item Price': row[hIP], 'Item Weight': weightCount[rowNum][2],
            'Item Weight Unit': 'lb', 'Order Currency': 'USD', 'Order Weight': weightCount[rowNum][3], 'Order Weight Unit': 'lb',
            'Order Amount': row[hOA]})
        rowNum+=1

    inputFile.close()
    shutil.move(file, '.\\processed')
    outputFile.close()
    # confirmation in terminal window
    print(file + ' is done processing')

print('')
print('Done generating shippoOrders.csv')
